# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Packer.gitlab-ci.yml

image:
  name: hashicorp/packer:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - packer --version

stages:
  - validate
  - build
  - test
  - deploy

validate:
  stage: validate
  script:
    # - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer validate
    - find provider -name '*.pkr.hcl' -print0 | xargs -t0n1 packer validate

build:
  stage: deploy
  environment: production
  script:
    # - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build
    # - BOX_VARIANT="minimal" make
    # - BOX_VARIANT="minimal-lvm" make
    # - BOX_VARIANT="minimal-cloud-init" make
    # - BOX_VARIANT="minimal-cloud-init-lvm" make
    # - BOX_VARIANT="minimal-vmi" make
    # - BOX_VARIANT="minimal-vmi-lvm" make
    - packer build -force -var-file=Rocky-8.8-x86_64-minimal-en_US.pkrvars.hcl provider/libvirt/Rocky-8-minimal.pkr.hcl
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
